project:
  name: zhc-edges-plugin
  description: A plugin system for ZHC edges
  longDescription: A plugin system that provides APIs and tools for ZHC edges
  links:
    homepage: https://github.com/zhenhuicai/zhc-edges-plugin
  inceptionYear: '2025'
  versionPattern: 'default'

release:
  github:
    active: ALWAYS
    token: '{{ env.JRELEASER_GITHUB_TOKEN }}'
    owner: zhenhuicai
    name: zhc-edges-plugin

signing:
  active: ALWAYS
  armored: true
  publicKey: "{{ env.GPG_KEY_ID }}"
  privateKey: "{{ env.GPG_PRIVATE_KEY }}"
  passphrase: "{{ env.GPG_PASSPHRASE }}"

deploy:
  maven:
    nexus2:
      mavenCentral:
        active: ALWAYS
        url: https://s01.oss.sonatype.org/service/local
        snapshotUrl: https://s01.oss.sonatype.org/content/repositories/snapshots/
        stagingRepository: build/staging-deploy
        username: "{{ env.SONATYPE_USER_NAME }}"
        password: "{{ env.SONATYPE_PASS_WORD }}"

distributions:
  plugins-api:
    artifacts:
      - path: "{{ projectDir }}/plugins-api/build/libs/plugins-api-{{ projectVersion }}.jar"
        groupId: com.zhm.edges
        artifactId: plugins-api
        version: "{{ projectVersion }}"
      - path: "{{ projectDir }}/plugins-api/build/libs/plugins-api-{{ projectVersion }}-sources.jar"
        groupId: com.zhm.edges
        artifactId: plugins-api
        version: "{{ projectVersion }}"
        classifier: sources
      - path: "{{ projectDir }}/plugins-api/build/libs/plugins-api-{{ projectVersion }}-javadoc.jar"
        groupId: com.zhm.edges
        artifactId: plugins-api
        version: "{{ projectVersion }}"
        classifier: javadoc
    pom:
      name: ZHC Edges Plugins API
      description: API module for ZHC Edges plugin system
      inceptionYear: '2025'
      url: https://github.com/zhenhuicai/zhc-edges-plugin
      licenses:
        - name: GNU Lesser General Public License v3.0
          url: https://www.gnu.org/licenses/lgpl-3.0.en.html
      developers:
        - id: tao.fang
          name: tao.fang
          email: tao.fang@gongkong.com
      scm:
        connection: scm:git:https://github.com/zhenhuicai/zhc-edges-plugin.git
        developerConnection: scm:git:ssh://github.com/zhenhuicai/zhc-edges-plugin.git
        url: https://github.com/zhenhuicai/zhc-edges-plugin

  plugins-test-support:
    artifacts:
      - path: "{{ projectDir }}/plugins-test-support/build/libs/plugins-test-support-{{ projectVersion }}.jar"
        groupId: com.zhm.edges
        artifactId: plugins-test-support
        version: "{{ projectVersion }}"
      - path: "{{ projectDir }}/plugins-test-support/build/libs/plugins-test-support-{{ projectVersion }}-sources.jar"
        groupId: com.zhm.edges
        artifactId: plugins-test-support
        version: "{{ projectVersion }}"
        classifier: sources
      - path: "{{ projectDir }}/plugins-test-support/build/libs/plugins-test-support-{{ projectVersion }}-javadoc.jar"
        groupId: com.zhm.edges
        artifactId: plugins-test-support
        version: "{{ projectVersion }}"
        classifier: javadoc
    pom:
      name: ZHC Edges Plugins Test Support
      description: Test support module for ZHC Edges plugin system
      inceptionYear: '2025'
      url: https://github.com/zhenhuicai/zhc-edges-plugin
      licenses:
        - name: GNU Lesser General Public License v3.0
          url: https://www.gnu.org/licenses/lgpl-3.0.en.html
      developers:
        - id: tao.fang
          name: tao.fang
          email: tao.fang@gongkong.com
      scm:
        connection: scm:git:https://github.com/zhenhuicai/zhc-edges-plugin.git
        developerConnection: scm:git:ssh://github.com/zhenhuicai/zhc-edges-plugin.git
        url: https://github.com/zhenhuicai/zhc-edges-plugin